/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

/**
 *
 * @author Adriana
 */
public class PnlDireccion extends javax.swing.JPanel {

    PrincipalControlador controlador;

    public void setControlador(PrincipalControlador controlador) {
        this.controlador = controlador;
    }
    
    
    /**
     * Creates new form pnlDireccion
     */
    public PnlDireccion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCalleBecado = new javax.swing.JTextField();
        txtNumBecado = new javax.swing.JTextField();
        txtColonia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIntBecado = new javax.swing.JTextField();
        txtCpBecado = new javax.swing.JTextField();
        txtCiudadBecado = new javax.swing.JTextField();
        lblAgregarDireccion = new javax.swing.JLabel();

        jTextField5.setText("jTextField1");

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(700, 70));

        jPanel1.setLayout(new java.awt.GridLayout(4, 3));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Calle");
        jPanel1.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Numero");
        jPanel1.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Int");
        jPanel1.add(jLabel3);

        txtCalleBecado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCalleBecadoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCalleBecado);

        txtNumBecado.setPreferredSize(new java.awt.Dimension(5, 13));
        txtNumBecado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumBecadoActionPerformed(evt);
            }
        });
        jPanel1.add(txtNumBecado);
        jPanel1.add(txtColonia);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("C.P.");
        jPanel1.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Colonia");
        jPanel1.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Ciudad");
        jPanel1.add(jLabel6);
        jPanel1.add(txtIntBecado);

        txtCpBecado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpBecadoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCpBecado);
        jPanel1.add(txtCiudadBecado);

        lblAgregarDireccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgregarDireccion.setText("Add");
        lblAgregarDireccion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAgregarDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAgregarDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCalleBecadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCalleBecadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCalleBecadoActionPerformed

    private void txtNumBecadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumBecadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumBecadoActionPerformed

    private void txtCpBecadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpBecadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpBecadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lblAgregarDireccion;
    private javax.swing.JTextField txtCalleBecado;
    private javax.swing.JTextField txtCiudadBecado;
    private javax.swing.JTextField txtColonia;
    private javax.swing.JTextField txtCpBecado;
    private javax.swing.JTextField txtIntBecado;
    private javax.swing.JTextField txtNumBecado;
    // End of variables declaration//GEN-END:variables
}
