/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

/**
 *
 * @author Adriana
 */
public class VistaCobranza extends javax.swing.JPanel {
    
    PrincipalControlador controlador;

    public void setControlador(PrincipalControlador controlador) {
        this.controlador = controlador;
    }

    /**
     * Creates new form PnlCobranza
     */
    public VistaCobranza() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlInfoBecario = new javax.swing.JPanel();
        PnlInfBecarioI = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFolio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPrograma = new javax.swing.JTextField();
        txtNombreBecario = new javax.swing.JTextField();
        PnlCargos = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jpnlListaSemestreCargos = new javax.swing.JPanel();
        TxtSemSC22 = new javax.swing.JTextField();
        TxtSemSC12 = new javax.swing.JTextField();
        TxtSemSC13 = new javax.swing.JTextField();
        TxtSemSC14 = new javax.swing.JTextField();
        TxtSemSC15 = new javax.swing.JTextField();
        TxtSemSC16 = new javax.swing.JTextField();
        TxtSemSC17 = new javax.swing.JTextField();
        TxtSemSC18 = new javax.swing.JTextField();
        TxtSemSC19 = new javax.swing.JTextField();
        TxtSemSC20 = new javax.swing.JTextField();
        TxtSemSC21 = new javax.swing.JTextField();
        TxtSemSC23 = new javax.swing.JTextField();
        TxtSemSC24 = new javax.swing.JTextField();
        TxtSemSC25 = new javax.swing.JTextField();
        TxtSemSC26 = new javax.swing.JTextField();
        TxtSemSC27 = new javax.swing.JTextField();
        TxtSemSC28 = new javax.swing.JTextField();
        TxtSemSC29 = new javax.swing.JTextField();
        TxtSemSC30 = new javax.swing.JTextField();
        TxtSemSC31 = new javax.swing.JTextField();
        TxtSemSC32 = new javax.swing.JTextField();
        TxtSemSC33 = new javax.swing.JTextField();
        TxtSemSC34 = new javax.swing.JTextField();
        TxtSemSC35 = new javax.swing.JTextField();
        jpnlListaDocumentos5 = new javax.swing.JPanel();
        TxtCargo11 = new javax.swing.JTextField();
        TxtCargo21 = new javax.swing.JTextField();
        TxtCargo12 = new javax.swing.JTextField();
        TxtCargo22 = new javax.swing.JTextField();
        TxtCargo13 = new javax.swing.JTextField();
        TxtCargo23 = new javax.swing.JTextField();
        TxtCargo14 = new javax.swing.JTextField();
        TxtCargo24 = new javax.swing.JTextField();
        TxtCargo15 = new javax.swing.JTextField();
        TxtCargo25 = new javax.swing.JTextField();
        TxtCargo16 = new javax.swing.JTextField();
        TxtCargo26 = new javax.swing.JTextField();
        TxtCargo17 = new javax.swing.JTextField();
        TxtCargo27 = new javax.swing.JTextField();
        TxtCargo18 = new javax.swing.JTextField();
        TxtCargo28 = new javax.swing.JTextField();
        TxtCargo19 = new javax.swing.JTextField();
        TxtCargo29 = new javax.swing.JTextField();
        TxtCargo110 = new javax.swing.JTextField();
        TxtCargo210 = new javax.swing.JTextField();
        TxtCargo111 = new javax.swing.JTextField();
        TxtCargo211 = new javax.swing.JTextField();
        TxtCargo112 = new javax.swing.JTextField();
        TxtCargo212 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCobranza = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtTotalCargos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTotalAbonos = new javax.swing.JTextField();
        jpnlAreaBotones = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();

        PnlInfoBecario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informacion del Becario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 10))); // NOI18N
        PnlInfoBecario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PnlInfBecarioI.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Folio:");

        txtFolio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFolio.setForeground(new java.awt.Color(255, 0, 0));
        txtFolio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFolio.setDisabledTextColor(new java.awt.Color(60, 60, 60));
        txtFolio.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Programa:");

        txtPrograma.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPrograma.setForeground(new java.awt.Color(255, 0, 0));
        txtPrograma.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPrograma.setDisabledTextColor(new java.awt.Color(60, 60, 60));
        txtPrograma.setEnabled(false);
        txtPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProgramaActionPerformed(evt);
            }
        });

        txtNombreBecario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNombreBecario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreBecario.setDisabledTextColor(new java.awt.Color(60, 60, 60));
        txtNombreBecario.setEnabled(false);
        txtNombreBecario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreBecarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlInfBecarioILayout = new javax.swing.GroupLayout(PnlInfBecarioI);
        PnlInfBecarioI.setLayout(PnlInfBecarioILayout);
        PnlInfBecarioILayout.setHorizontalGroup(
            PnlInfBecarioILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlInfBecarioILayout.createSequentialGroup()
                .addGroup(PnlInfBecarioILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlInfBecarioILayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtNombreBecario))
                    .addGroup(PnlInfBecarioILayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 80, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PnlInfBecarioILayout.setVerticalGroup(
            PnlInfBecarioILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlInfBecarioILayout.createSequentialGroup()
                .addGroup(PnlInfBecarioILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreBecario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PnlInfoBecario.add(PnlInfBecarioI, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 17, 680, 70));

        PnlCargos.setBorder(javax.swing.BorderFactory.createTitledBorder("Cargos"));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel45.setText("Cargo");

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel44.setText("Periodo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel44))
        );

        jpnlListaSemestreCargos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpnlListaSemestreCargos.setMaximumSize(new java.awt.Dimension(141, 174));
        jpnlListaSemestreCargos.setLayout(new java.awt.GridLayout(24, 1));

        TxtSemSC22.setBackground(new java.awt.Color(204, 255, 204));
        TxtSemSC22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtSemSC22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtSemSC22.setText("Transf 1 Semestre1");
        TxtSemSC22.setBorder(null);
        TxtSemSC22.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtSemSC22.setEnabled(false);
        TxtSemSC22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSemSC22ActionPerformed(evt);
            }
        });
        jpnlListaSemestreCargos.add(TxtSemSC22);

        TxtSemSC12.setBackground(new java.awt.Color(204, 255, 204));
        TxtSemSC12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtSemSC12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtSemSC12.setText("Transf 2 Semestre 1");
        TxtSemSC12.setBorder(null);
        TxtSemSC12.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtSemSC12.setEnabled(false);
        TxtSemSC12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSemSC12ActionPerformed(evt);
            }
        });
        jpnlListaSemestreCargos.add(TxtSemSC12);

        TxtSemSC13.setBackground(new java.awt.Color(204, 204, 255));
        TxtSemSC13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtSemSC13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtSemSC13.setText("Transf 1 Semestre 2");
        TxtSemSC13.setBorder(null);
        TxtSemSC13.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtSemSC13.setEnabled(false);
        TxtSemSC13.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        TxtSemSC13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSemSC13ActionPerformed(evt);
            }
        });
        jpnlListaSemestreCargos.add(TxtSemSC13);

        TxtSemSC14.setBackground(new java.awt.Color(204, 204, 255));
        TxtSemSC14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtSemSC14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtSemSC14.setText("Transf 2 Semestre 2");
        TxtSemSC14.setBorder(null);
        TxtSemSC14.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtSemSC14.setEnabled(false);
        TxtSemSC14.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        TxtSemSC14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSemSC14ActionPerformed(evt);
            }
        });
        jpnlListaSemestreCargos.add(TxtSemSC14);

        TxtSemSC15.setBackground(new java.awt.Color(204, 255, 204));
        TxtSemSC15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtSemSC15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtSemSC15.setText("Transf 1 Semestre 3");
        TxtSemSC15.setBorder(null);
        TxtSemSC15.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtSemSC15.setEnabled(false);
        TxtSemSC15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSemSC15ActionPerformed(evt);
            }
        });
        jpnlListaSemestreCargos.add(TxtSemSC15);

        TxtSemSC16.setBackground(new java.awt.Color(204, 255, 204));
        TxtSemSC16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtSemSC16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtSemSC16.setText("Transf 2 Semestre 3");
        TxtSemSC16.setBorder(null);
        TxtSemSC16.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtSemSC16.setEnabled(false);
        TxtSemSC16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSemSC16ActionPerformed(evt);
            }
        });
        jpnlListaSemestreCargos.add(TxtSemSC16);

        TxtSemSC17.setBackground(new java.awt.Color(204, 204, 255));
        TxtSemSC17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtSemSC17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtSemSC17.setText("Transf 1 Semestre 4");
        TxtSemSC17.setBorder(null);
        TxtSemSC17.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtSemSC17.setEnabled(false);
        TxtSemSC17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSemSC17ActionPerformed(evt);
            }
        });
        jpnlListaSemestreCargos.add(TxtSemSC17);

        TxtSemSC18.setBackground(new java.awt.Color(204, 204, 255));
        TxtSemSC18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtSemSC18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtSemSC18.setText("Transf 2 Semestre 4");
        TxtSemSC18.setBorder(null);
        TxtSemSC18.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtSemSC18.setEnabled(false);
        TxtSemSC18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSemSC18ActionPerformed(evt);
            }
        });
        jpnlListaSemestreCargos.add(TxtSemSC18);

        TxtSemSC19.setBackground(new java.awt.Color(204, 255, 204));
        TxtSemSC19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtSemSC19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtSemSC19.setText("Transf 1 Semestre 5");
        TxtSemSC19.setBorder(null);
        TxtSemSC19.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtSemSC19.setEnabled(false);
        TxtSemSC19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSemSC19ActionPerformed(evt);
            }
        });
        jpnlListaSemestreCargos.add(TxtSemSC19);

        TxtSemSC20.setEditable(false);
        TxtSemSC20.setBackground(new java.awt.Color(204, 255, 204));
        TxtSemSC20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtSemSC20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtSemSC20.setText("Trasnf 2 Semestre 5");
        TxtSemSC20.setBorder(null);
        TxtSemSC20.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtSemSC20.setEnabled(false);
        TxtSemSC20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSemSC20ActionPerformed(evt);
            }
        });
        jpnlListaSemestreCargos.add(TxtSemSC20);

        TxtSemSC21.setEditable(false);
        TxtSemSC21.setBackground(new java.awt.Color(204, 255, 204));
        TxtSemSC21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtSemSC21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtSemSC21.setText("Trasnf 1 Semestre 6");
        TxtSemSC21.setBorder(null);
        TxtSemSC21.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtSemSC21.setEnabled(false);
        TxtSemSC21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSemSC21ActionPerformed(evt);
            }
        });
        jpnlListaSemestreCargos.add(TxtSemSC21);

        TxtSemSC23.setEditable(false);
        TxtSemSC23.setBackground(new java.awt.Color(204, 255, 204));
        TxtSemSC23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtSemSC23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtSemSC23.setText("Trasnf 2 Semestre 6");
        TxtSemSC23.setBorder(null);
        TxtSemSC23.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtSemSC23.setEnabled(false);
        TxtSemSC23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSemSC23ActionPerformed(evt);
            }
        });
        jpnlListaSemestreCargos.add(TxtSemSC23);

        TxtSemSC24.setEditable(false);
        TxtSemSC24.setBackground(new java.awt.Color(204, 255, 204));
        TxtSemSC24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtSemSC24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtSemSC24.setText("Trasnf 1 Semestre 7");
        TxtSemSC24.setBorder(null);
        TxtSemSC24.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtSemSC24.setEnabled(false);
        TxtSemSC24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSemSC24ActionPerformed(evt);
            }
        });
        jpnlListaSemestreCargos.add(TxtSemSC24);

        TxtSemSC25.setEditable(false);
        TxtSemSC25.setBackground(new java.awt.Color(204, 255, 204));
        TxtSemSC25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtSemSC25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtSemSC25.setText("Trasnf 2 Semestre 7");
        TxtSemSC25.setBorder(null);
        TxtSemSC25.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtSemSC25.setEnabled(false);
        TxtSemSC25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSemSC25ActionPerformed(evt);
            }
        });
        jpnlListaSemestreCargos.add(TxtSemSC25);

        TxtSemSC26.setEditable(false);
        TxtSemSC26.setBackground(new java.awt.Color(204, 255, 204));
        TxtSemSC26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtSemSC26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtSemSC26.setText("Trasnf 1 Semestre 8");
        TxtSemSC26.setBorder(null);
        TxtSemSC26.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtSemSC26.setEnabled(false);
        TxtSemSC26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSemSC26ActionPerformed(evt);
            }
        });
        jpnlListaSemestreCargos.add(TxtSemSC26);

        TxtSemSC27.setEditable(false);
        TxtSemSC27.setBackground(new java.awt.Color(204, 255, 204));
        TxtSemSC27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtSemSC27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtSemSC27.setText("Trasnf 2 Semestre 8");
        TxtSemSC27.setBorder(null);
        TxtSemSC27.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtSemSC27.setEnabled(false);
        TxtSemSC27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSemSC27ActionPerformed(evt);
            }
        });
        jpnlListaSemestreCargos.add(TxtSemSC27);

        TxtSemSC28.setEditable(false);
        TxtSemSC28.setBackground(new java.awt.Color(204, 255, 204));
        TxtSemSC28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtSemSC28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtSemSC28.setText("Trasnf 1 Semestre 9");
        TxtSemSC28.setBorder(null);
        TxtSemSC28.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtSemSC28.setEnabled(false);
        TxtSemSC28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSemSC28ActionPerformed(evt);
            }
        });
        jpnlListaSemestreCargos.add(TxtSemSC28);

        TxtSemSC29.setEditable(false);
        TxtSemSC29.setBackground(new java.awt.Color(204, 255, 204));
        TxtSemSC29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtSemSC29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtSemSC29.setText("Trasnf 2 Semestre 9");
        TxtSemSC29.setBorder(null);
        TxtSemSC29.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtSemSC29.setEnabled(false);
        TxtSemSC29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSemSC29ActionPerformed(evt);
            }
        });
        jpnlListaSemestreCargos.add(TxtSemSC29);

        TxtSemSC30.setEditable(false);
        TxtSemSC30.setBackground(new java.awt.Color(204, 255, 204));
        TxtSemSC30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtSemSC30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtSemSC30.setText("Trasnf 1 Semestre 10");
        TxtSemSC30.setBorder(null);
        TxtSemSC30.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtSemSC30.setEnabled(false);
        TxtSemSC30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSemSC30ActionPerformed(evt);
            }
        });
        jpnlListaSemestreCargos.add(TxtSemSC30);

        TxtSemSC31.setEditable(false);
        TxtSemSC31.setBackground(new java.awt.Color(204, 255, 204));
        TxtSemSC31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtSemSC31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtSemSC31.setText("Trasnf 2 Semestre 10");
        TxtSemSC31.setBorder(null);
        TxtSemSC31.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtSemSC31.setEnabled(false);
        TxtSemSC31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSemSC31ActionPerformed(evt);
            }
        });
        jpnlListaSemestreCargos.add(TxtSemSC31);

        TxtSemSC32.setEditable(false);
        TxtSemSC32.setBackground(new java.awt.Color(204, 255, 204));
        TxtSemSC32.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtSemSC32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtSemSC32.setText("Trasnf 1 Semestre 11");
        TxtSemSC32.setBorder(null);
        TxtSemSC32.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtSemSC32.setEnabled(false);
        TxtSemSC32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSemSC32ActionPerformed(evt);
            }
        });
        jpnlListaSemestreCargos.add(TxtSemSC32);

        TxtSemSC33.setEditable(false);
        TxtSemSC33.setBackground(new java.awt.Color(204, 255, 204));
        TxtSemSC33.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtSemSC33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtSemSC33.setText("Trasnf 2 Semestre 11");
        TxtSemSC33.setBorder(null);
        TxtSemSC33.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtSemSC33.setEnabled(false);
        TxtSemSC33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSemSC33ActionPerformed(evt);
            }
        });
        jpnlListaSemestreCargos.add(TxtSemSC33);

        TxtSemSC34.setEditable(false);
        TxtSemSC34.setBackground(new java.awt.Color(204, 255, 204));
        TxtSemSC34.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtSemSC34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtSemSC34.setText("Trasnf 1 Semestre 12");
        TxtSemSC34.setBorder(null);
        TxtSemSC34.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtSemSC34.setEnabled(false);
        TxtSemSC34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSemSC34ActionPerformed(evt);
            }
        });
        jpnlListaSemestreCargos.add(TxtSemSC34);

        TxtSemSC35.setEditable(false);
        TxtSemSC35.setBackground(new java.awt.Color(204, 255, 204));
        TxtSemSC35.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtSemSC35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtSemSC35.setText("Trasnf 2 Semestre 12");
        TxtSemSC35.setBorder(null);
        TxtSemSC35.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtSemSC35.setEnabled(false);
        TxtSemSC35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSemSC35ActionPerformed(evt);
            }
        });
        jpnlListaSemestreCargos.add(TxtSemSC35);

        jpnlListaDocumentos5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpnlListaDocumentos5.setMaximumSize(new java.awt.Dimension(141, 174));
        jpnlListaDocumentos5.setLayout(new java.awt.GridLayout(24, 1));
        jpnlListaDocumentos5.add(TxtCargo11);
        jpnlListaDocumentos5.add(TxtCargo21);
        jpnlListaDocumentos5.add(TxtCargo12);
        jpnlListaDocumentos5.add(TxtCargo22);
        jpnlListaDocumentos5.add(TxtCargo13);
        jpnlListaDocumentos5.add(TxtCargo23);
        jpnlListaDocumentos5.add(TxtCargo14);
        jpnlListaDocumentos5.add(TxtCargo24);
        jpnlListaDocumentos5.add(TxtCargo15);
        jpnlListaDocumentos5.add(TxtCargo25);
        jpnlListaDocumentos5.add(TxtCargo16);
        jpnlListaDocumentos5.add(TxtCargo26);
        jpnlListaDocumentos5.add(TxtCargo17);
        jpnlListaDocumentos5.add(TxtCargo27);
        jpnlListaDocumentos5.add(TxtCargo18);
        jpnlListaDocumentos5.add(TxtCargo28);
        jpnlListaDocumentos5.add(TxtCargo19);
        jpnlListaDocumentos5.add(TxtCargo29);
        jpnlListaDocumentos5.add(TxtCargo110);
        jpnlListaDocumentos5.add(TxtCargo210);
        jpnlListaDocumentos5.add(TxtCargo111);
        jpnlListaDocumentos5.add(TxtCargo211);
        jpnlListaDocumentos5.add(TxtCargo112);
        jpnlListaDocumentos5.add(TxtCargo212);

        javax.swing.GroupLayout PnlCargosLayout = new javax.swing.GroupLayout(PnlCargos);
        PnlCargos.setLayout(PnlCargosLayout);
        PnlCargosLayout.setHorizontalGroup(
            PnlCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlCargosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PnlCargosLayout.createSequentialGroup()
                        .addComponent(jpnlListaSemestreCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jpnlListaDocumentos5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        PnlCargosLayout.setVerticalGroup(
            PnlCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlCargosLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnlListaSemestreCargos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnlListaDocumentos5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Abonos"));

        tblCobranza.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha Aplicación", "Abono", "Referencia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCobranza);
        if (tblCobranza.getColumnModel().getColumnCount() > 0) {
            tblCobranza.getColumnModel().getColumn(0).setResizable(false);
            tblCobranza.getColumnModel().getColumn(1).setResizable(false);
            tblCobranza.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("CARGOS   $");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("ABONOS   $");

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar_cambios.png"))); // NOI18N
        btnGuardar.setToolTipText("Guardar Registro");
        btnGuardar.setPreferredSize(new java.awt.Dimension(160, 29));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        btnSalir.setToolTipText("Salir de Pantalla");
        btnSalir.setPreferredSize(new java.awt.Dimension(160, 29));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imprimir.png"))); // NOI18N
        btnImprimir.setToolTipText("IMPRESION GENERAL BECARIO");
        btnImprimir.setPreferredSize(new java.awt.Dimension(160, 29));
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnlAreaBotonesLayout = new javax.swing.GroupLayout(jpnlAreaBotones);
        jpnlAreaBotones.setLayout(jpnlAreaBotonesLayout);
        jpnlAreaBotonesLayout.setHorizontalGroup(
            jpnlAreaBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlAreaBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlAreaBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImprimir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnlAreaBotonesLayout.setVerticalGroup(
            jpnlAreaBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlAreaBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3)
                        .addGap(60, 60, 60)
                        .addComponent(txtTotalCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotalAbonos, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(PnlInfoBecario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PnlCargos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpnlAreaBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PnlInfoBecario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PnlCargos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jpnlAreaBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTotalCargos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtTotalAbonos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProgramaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProgramaActionPerformed

    private void txtNombreBecarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreBecarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreBecarioActionPerformed

    private void TxtSemSC22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSemSC22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSemSC22ActionPerformed

    private void TxtSemSC12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSemSC12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSemSC12ActionPerformed

    private void TxtSemSC13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSemSC13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSemSC13ActionPerformed

    private void TxtSemSC14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSemSC14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSemSC14ActionPerformed

    private void TxtSemSC15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSemSC15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSemSC15ActionPerformed

    private void TxtSemSC16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSemSC16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSemSC16ActionPerformed

    private void TxtSemSC17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSemSC17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSemSC17ActionPerformed

    private void TxtSemSC18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSemSC18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSemSC18ActionPerformed

    private void TxtSemSC19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSemSC19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSemSC19ActionPerformed

    private void TxtSemSC20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSemSC20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSemSC20ActionPerformed

    private void TxtSemSC21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSemSC21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSemSC21ActionPerformed

    private void TxtSemSC23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSemSC23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSemSC23ActionPerformed

    private void TxtSemSC24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSemSC24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSemSC24ActionPerformed

    private void TxtSemSC25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSemSC25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSemSC25ActionPerformed

    private void TxtSemSC26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSemSC26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSemSC26ActionPerformed

    private void TxtSemSC27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSemSC27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSemSC27ActionPerformed

    private void TxtSemSC28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSemSC28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSemSC28ActionPerformed

    private void TxtSemSC29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSemSC29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSemSC29ActionPerformed

    private void TxtSemSC30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSemSC30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSemSC30ActionPerformed

    private void TxtSemSC31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSemSC31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSemSC31ActionPerformed

    private void TxtSemSC32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSemSC32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSemSC32ActionPerformed

    private void TxtSemSC33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSemSC33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSemSC33ActionPerformed

    private void TxtSemSC34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSemSC34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSemSC34ActionPerformed

    private void TxtSemSC35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSemSC35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSemSC35ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        controlador.updateKardexBecario();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        controlador.cerrarSesion();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        controlador.creaReporteIndividual();
    }//GEN-LAST:event_btnImprimirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JPanel PnlCargos;
    private javax.swing.JPanel PnlInfBecarioI;
    private javax.swing.JPanel PnlInfoBecario;
    private javax.swing.JTextField TxtCargo11;
    private javax.swing.JTextField TxtCargo110;
    private javax.swing.JTextField TxtCargo111;
    private javax.swing.JTextField TxtCargo112;
    private javax.swing.JTextField TxtCargo12;
    private javax.swing.JTextField TxtCargo13;
    private javax.swing.JTextField TxtCargo14;
    private javax.swing.JTextField TxtCargo15;
    private javax.swing.JTextField TxtCargo16;
    private javax.swing.JTextField TxtCargo17;
    private javax.swing.JTextField TxtCargo18;
    private javax.swing.JTextField TxtCargo19;
    private javax.swing.JTextField TxtCargo21;
    private javax.swing.JTextField TxtCargo210;
    private javax.swing.JTextField TxtCargo211;
    private javax.swing.JTextField TxtCargo212;
    private javax.swing.JTextField TxtCargo22;
    private javax.swing.JTextField TxtCargo23;
    private javax.swing.JTextField TxtCargo24;
    private javax.swing.JTextField TxtCargo25;
    private javax.swing.JTextField TxtCargo26;
    private javax.swing.JTextField TxtCargo27;
    private javax.swing.JTextField TxtCargo28;
    private javax.swing.JTextField TxtCargo29;
    protected javax.swing.JTextField TxtSemSC12;
    protected javax.swing.JTextField TxtSemSC13;
    protected javax.swing.JTextField TxtSemSC14;
    protected javax.swing.JTextField TxtSemSC15;
    protected javax.swing.JTextField TxtSemSC16;
    protected javax.swing.JTextField TxtSemSC17;
    protected javax.swing.JTextField TxtSemSC18;
    protected javax.swing.JTextField TxtSemSC19;
    protected javax.swing.JTextField TxtSemSC20;
    protected javax.swing.JTextField TxtSemSC21;
    protected javax.swing.JTextField TxtSemSC22;
    protected javax.swing.JTextField TxtSemSC23;
    protected javax.swing.JTextField TxtSemSC24;
    protected javax.swing.JTextField TxtSemSC25;
    protected javax.swing.JTextField TxtSemSC26;
    protected javax.swing.JTextField TxtSemSC27;
    protected javax.swing.JTextField TxtSemSC28;
    protected javax.swing.JTextField TxtSemSC29;
    protected javax.swing.JTextField TxtSemSC30;
    protected javax.swing.JTextField TxtSemSC31;
    protected javax.swing.JTextField TxtSemSC32;
    protected javax.swing.JTextField TxtSemSC33;
    protected javax.swing.JTextField TxtSemSC34;
    protected javax.swing.JTextField TxtSemSC35;
    protected javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImprimir;
    protected javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpnlAreaBotones;
    protected javax.swing.JPanel jpnlListaDocumentos5;
    protected javax.swing.JPanel jpnlListaSemestreCargos;
    protected javax.swing.JTable tblCobranza;
    protected javax.swing.JTextField txtFolio;
    protected javax.swing.JTextField txtNombreBecario;
    protected javax.swing.JTextField txtPrograma;
    protected javax.swing.JTextField txtTotalAbonos;
    protected javax.swing.JTextField txtTotalCargos;
    // End of variables declaration//GEN-END:variables
}
