/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adris.vistas;

/**
 *
 * @author Adriana
 */
public class jfrmeDireccionBecado extends javax.swing.JFrame {

    /**
     * Creates new form jfrmeDireccionBecado
     */
    public jfrmeDireccionBecado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDirNoextBecado = new javax.swing.JTextField();
        txtDirCalleBecado = new javax.swing.JTextField();
        txtDirNointBecado = new javax.swing.JTextField();
        txtDirColoniaBecado = new javax.swing.JTextField();
        txtDirCpBecado = new javax.swing.JTextField();
        txtDirCiudadBecado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dirección Becario");

        txtDirNoextBecado.setText("No");

        txtDirCalleBecado.setText("Calle");
        txtDirCalleBecado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirCalleBecadoActionPerformed(evt);
            }
        });

        txtDirNointBecado.setText("NoInt");
        txtDirNointBecado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirNointBecadoActionPerformed(evt);
            }
        });

        txtDirColoniaBecado.setText("Colonia");
        txtDirColoniaBecado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirColoniaBecadoActionPerformed(evt);
            }
        });

        txtDirCpBecado.setText("C.P.");
        txtDirCpBecado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirCpBecadoActionPerformed(evt);
            }
        });

        txtDirCiudadBecado.setText("Ciudad");
        txtDirCiudadBecado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirCiudadBecadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDirCalleBecado, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDirNoextBecado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDirNointBecado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDirColoniaBecado, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDirCpBecado, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDirCiudadBecado, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDirNoextBecado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDirCalleBecado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDirNointBecado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDirColoniaBecado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDirCpBecado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDirCiudadBecado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDirCalleBecadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirCalleBecadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirCalleBecadoActionPerformed

    private void txtDirNointBecadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirNointBecadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirNointBecadoActionPerformed

    private void txtDirColoniaBecadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirColoniaBecadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirColoniaBecadoActionPerformed

    private void txtDirCpBecadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirCpBecadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirCpBecadoActionPerformed

    private void txtDirCiudadBecadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirCiudadBecadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirCiudadBecadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmeDireccionBecado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmeDireccionBecado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmeDireccionBecado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmeDireccionBecado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmeDireccionBecado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField txtDirCalleBecado;
    private javax.swing.JTextField txtDirCiudadBecado;
    private javax.swing.JTextField txtDirColoniaBecado;
    private javax.swing.JTextField txtDirCpBecado;
    private javax.swing.JTextField txtDirNoextBecado;
    private javax.swing.JTextField txtDirNointBecado;
    // End of variables declaration//GEN-END:variables
}
