/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adris.vistas;

import principal.*;

/**
 *
 * @author Adriana
 */
public class PnlHermanos extends javax.swing.JPanel {
    
    PrincipalControlador controlador;

    public void setControlador(PrincipalControlador controlador) {
        this.controlador = controlador;
    }

    /**
     * Creates new form pnlHermanos
     */
    public PnlHermanos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblParentesco1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblParentesco5 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtNombresPariente = new javax.swing.JTextField();
        txtApPaternoPariente = new javax.swing.JTextField();
        txtApMaternoPariente = new javax.swing.JTextField();
        cmbNivelEstudiosHermano = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaComentario = new javax.swing.JTextPane();
        lblAgregarHermano = new javax.swing.JLabel();
        lblBorrarHermano = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(999, 60));

        jPanel1.setLayout(new java.awt.GridLayout(2, 4, 10, 0));

        lblParentesco1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblParentesco1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblParentesco1.setText("Nombre(s)");
        jPanel1.add(lblParentesco1);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Ap Paterno");
        jPanel1.add(jLabel21);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("Ap Materno");
        jPanel1.add(jLabel22);

        lblParentesco5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblParentesco5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblParentesco5.setText("Nivel de Estudios");
        jPanel1.add(lblParentesco5);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("Comentario");
        jPanel1.add(jLabel23);

        txtNombresPariente.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jPanel1.add(txtNombresPariente);

        txtApPaternoPariente.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jPanel1.add(txtApPaternoPariente);

        txtApMaternoPariente.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jPanel1.add(txtApMaternoPariente);

        cmbNivelEstudiosHermano.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jPanel1.add(cmbNivelEstudiosHermano);

        txtAreaComentario.setBorder(null);
        txtAreaComentario.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jScrollPane1.setViewportView(txtAreaComentario);

        jPanel1.add(jScrollPane1);

        lblAgregarHermano.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgregarHermano.setText("Add");
        lblAgregarHermano.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblAgregarHermano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAgregarHermanoMouseClicked(evt);
            }
        });

        lblBorrarHermano.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBorrarHermano.setText("Delete");
        lblBorrarHermano.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblBorrarHermano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBorrarHermanoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 929, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAgregarHermano, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBorrarHermano, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAgregarHermano)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBorrarHermano)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblAgregarHermanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarHermanoMouseClicked
        controlador.agregaJPanel(this);
    }//GEN-LAST:event_lblAgregarHermanoMouseClicked

    private void lblBorrarHermanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBorrarHermanoMouseClicked
        controlador.borraJpanel(this);
    }//GEN-LAST:event_lblBorrarHermanoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JComboBox cmbNivelEstudiosHermano;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JLabel lblAgregarHermano;
    protected javax.swing.JLabel lblBorrarHermano;
    private javax.swing.JLabel lblParentesco1;
    private javax.swing.JLabel lblParentesco5;
    protected javax.swing.JTextField txtApMaternoPariente;
    protected javax.swing.JTextField txtApPaternoPariente;
    protected javax.swing.JTextPane txtAreaComentario;
    protected javax.swing.JTextField txtNombresPariente;
    // End of variables declaration//GEN-END:variables
}
